### ISSUE TITLE
[Suggestion] Add Batch Processing

### ISSUE THREAD

**Issue by Suleman-Elahi** [bigbamboo-jp/cloud-ocr-snip#8]
Consider add the ability to use local images to process via OCR to make the use case broader.

**Comment by bigbamboo-jp** [comment]
Thank you for your feature request, Suleman.
I had considered batch processing before, but decided against it because OCR capabilities using cloud services like Google Cloud Vision were already supported by major Robotic process automation tools.
For now, this application has the ability to read characters in a single local image, so if you combine it with other tools, you can achieve batch processing on many images.
If you have any other questions, please feel free to contact me.
